import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
};

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response(null, { headers: corsHeaders });
  }

  console.log("Starting scheduled article generation...");

  try {
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseKey);

    // Check how many articles were published today
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    const todayIso = today.toISOString();

    const { count: articlesToday, error: countError } = await supabase
      .from("news_articles")
      .select("*", { count: "exact", head: true })
      .gte("published_at", todayIso);

    if (countError) {
      console.error("Error counting today's articles:", countError);
    }

    console.log(`Articles published today: ${articlesToday || 0}`);

    // Target: 3 articles per day maximum
    const targetDaily = 3;
    const remaining = targetDaily - (articlesToday || 0);

    if (remaining <= 0) {
      console.log("Daily article limit reached. Skipping generation.");
      return new Response(
        JSON.stringify({ 
          success: true, 
          message: "Daily limit reached", 
          articlesToday: articlesToday || 0 
        }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    // Get categories with fewer recent articles for balanced coverage
    const weekAgo = new Date();
    weekAgo.setDate(weekAgo.getDate() - 7);
    
    const { data: recentArticles } = await supabase
      .from("news_articles")
      .select("category")
      .gte("published_at", weekAgo.toISOString());

    // Count articles per category
    const categoryCounts: Record<string, number> = {};
    const allCategories = ["flight", "telecom", "bank", "energy", "ecommerce", "class_action"];
    
    allCategories.forEach(cat => categoryCounts[cat] = 0);
    recentArticles?.forEach(article => {
      if (categoryCounts[article.category] !== undefined) {
        categoryCounts[article.category]++;
      }
    });

    console.log("Category coverage this week:", categoryCounts);

    // Sort categories by least covered first
    const sortedCategories = Object.entries(categoryCounts)
      .sort((a, b) => a[1] - b[1])
      .map(([cat]) => cat);

    // Pick category with least coverage
    const targetCategory = sortedCategories[0];
    console.log(`Generating article for category: ${targetCategory}`);

    // Call the generate-news-article function
    const generateResponse = await fetch(`${supabaseUrl}/functions/v1/generate-news-article`, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${supabaseKey}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ 
        category: targetCategory,
        autoGenerated: true 
      }),
    });

    if (!generateResponse.ok) {
      const errorText = await generateResponse.text();
      console.error("Article generation failed:", errorText);
      return new Response(
        JSON.stringify({ success: false, error: errorText }),
        { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
      );
    }

    const result = await generateResponse.json();
    console.log("Article generated successfully:", result.title);

    return new Response(
      JSON.stringify({
        success: true,
        message: "Article generated",
        title: result.title,
        slug: result.slug,
        category: result.category,
        articlesToday: (articlesToday || 0) + 1,
        remainingToday: remaining - 1,
      }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : "Unknown error";
    console.error("Scheduled generation error:", errorMessage);
    return new Response(
      JSON.stringify({ success: false, error: errorMessage }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } }
    );
  }
});
